### ISSUE TITLE
Problem with activation

### ISSUE THREAD

**Issue by gemcave** [ChenxiiCheng/NextJS-DjangoREST-Blog#1]
When i activate it uses external environment instead internal venv, and why you have env instead of env. Pls i want explore django / react connection + tips and tricks from more mature dev than me. Thanks for oss.

**Comment by ChenxiiCheng** [comment]
@gemcave Hi, thanks for the issue. I think you can delete the server/env folder, and in the server folder, run `python -m venv ./env` to create a new virtual environment "env" folder. Then activate this virtual environment by running `source ./env/bin/activate` and install some packages, like djangorestframework, pillow (you can run the server directly if there are missing some packages, you can see the detailed error in the console and install missing packages)

You are free to use external environment, but I prefer to create a virtual environment within the project folder. When have many projects, I think this is easy to find where is the project virtual environment. If you use VSCode editor, make sure the Python Interpreter is using the /env/bin/python (or you can create .vscode folder, and within this folder create a settings.json)
```
{
  "python.pythonPath": "env/bin/python"      // the path of python interpreter within virtual environment
}
```
